volumes:
  wordpress_database:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/lleciak/data/wordpress
      o: bind

  mariadb_database:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: /home/lleciak/data/mariadb
      o: bind
  
networks:
  inception:
    name: inception
    driver: bridge

services:
  nginx:
    container_name: nginx
    volumes:
       - wordpress_database:/var/www/html/
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure
       
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
       - mariadb_database:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
  

    
  wordpress:
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volumes:
       - wordpress_database:/var/www/html
    restart: on-failure
    expose:
      - "9000"
